# https://travis-ci.org/#!/translate/pootle
language: python
python:
  - 2.6
  - 2.7
env:
  matrix:
    - DJANGO_VERSION=1.5.8 DATABASE_BACKEND=sqlite
    - DJANGO_VERSION=1.5.8 DATABASE_BACKEND=postgres
    - DJANGO_VERSION=1.5.8 DATABASE_BACKEND=mysql
    - DJANGO_VERSION=1.6.2 DATABASE_BACKEND=sqlite
    - DJANGO_VERSION=1.6.2 DATABASE_BACKEND=postgres
    - DJANGO_VERSION=1.6.2 DATABASE_BACKEND=mysql
cache:
  - apt
before_install:
  - travis_retry sudo apt-get install -qq bc
install:
  - travis_retry pip install -r requirements/travis.txt --timeout=240
  - travis_retry pip install "Django>=$DJANGO_VERSION,<"$(echo $(echo $DJANGO_VERSION | cut -d"." -f1,2) + 0.1 | bc) --timeout=240
  - pip freeze  # Print all installed versions for reference.
before_script:
  - if [[ $DATABASE_BACKEND == 'postgres' ]]; then psql -c 'create database pootle;' -U postgres; fi
  - if [[ $DATABASE_BACKEND == 'mysql' ]]; then mysql -e 'create database pootle;'; fi
script:
  - python -m compileall -q -f .
  - make docs
  - make build SHELL=/bin/bash TAIL='|tail -40; exit $$PIPESTATUS'
  - coverage run --parallel-mode manage.py syncdb --noinput --traceback
  - coverage run --parallel-mode manage.py migrate --traceback
  - coverage run --parallel-mode manage.py initdb --traceback
  - coverage run --parallel-mode ./manage.py runserver --traceback &
  - TESTPID=$!
  - sleep 20
  - kill -2 $TESTPID
  - tests/version-migration/migrate.sh
  - make pep8
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    on_failure: always
    on_success: change
services:
  - memcached
